services:
  - type: web
    name: actualizar-presentacion-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: "astute-dreamer-463903-s9-578f5ce1cd5e.json"
